version: '3'

services:
  # lb:
  #   image: haproxy
  #   ports:
  #     - '8080:8080'
  #   volumes:
  #     - ./haproxy:/usr/local/etc/haproxy
  lb:
    image: nginx
    ports:
      - '8080:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  ws1:
    image: sockets-scalability-example
    environment:
      - APP_ID=1111
      - REDIS_HOST=redis
  ws2:
    image: sockets-scalability-example
    environment:
      - APP_ID=2222
      - REDIS_HOST=redis
  ws3:
    image: sockets-scalability-example
    environment:
      - APP_ID=3333
      - REDIS_HOST=redis
  ws4:
    image: sockets-scalability-example
    environment:
      - APP_ID=4444
      - REDIS_HOST=redis
  redis:
    image: redis
    ports:
      - '6379:6379'
